### ISSUE TITLE
Mobile Style

### ISSUE THREAD

**Issue by fhebert-perkins** [BaySchoolCS2/ProjectRepo#71] opened 2015-05-08 03:45 UTC
We should have dedicated mobile style. While Bootstrap does do some it can look pretty wacky on mobile so we should make sure that everything has a mobile counterpart that looks good.

**Comment by michardy** [comment] 2015-05-08 03:49
Yes we need a mobile style.  The website is currently microscopic on Firefox or Chrome for Android.

**Comment by michardy** [comment] 2015-05-20 14:50
Duplicate of larger issue:
https://github.com/BaySchoolCS2/ProjectRepo/issues/42

**Closed as completed by michardy** 2015-05-20 14:50 UTC
Labels: enhancement, UI
